Repository carlosricov/Flask-Practice-Typer-Team3, pull requests merged in 2021-08, with the labels that each got.

#5 Add PR template to repo
  .github/pull_request_template.md
Labels: documentation

#7 Setup Flask App
  app/__init__.py
  app/templates/index.html
Labels: enhancement

#9 002 home page
  app/static/img/the_sea_turtle.ico
  app/static/js/animation.js
  app/static/styles/landing.css
  app/templates/base.html
  app/templates/index.html
Labels: enhancement

#13 004 link login
  app/templates/base.html
  app/templates/index-old.html
  app/templates/index.html
  app/templates/login.html
Labels: enhancement

#14 Added register.html & registerStyles.css
  app/static/styles/registerStyle.css
  app/templates/register.html
Labels: enhancement

#17 Link register
  app/__init__.py
  app/templates/index.html
  app/templates/register.html
Labels: bug, enhancement

#21 Update home header
  app/static/js/animation.js
  app/static/styles/header.css
  app/templates/index.html
Labels: enhancement

#19 Added return to home functionality and nav bar to login & register | minor bugs to fix in style
  app/static/styles/login.css
  app/static/styles/registerStyle.css
  app/templates/login.html
  app/templates/register.html
Labels: enhancement, help wanted

#24 Update reg and login
  .gitignore
  app/static/styles/login.css
  app/templates/index.html
  app/templates/login.html
  app/templates/register.html
Labels: bug, enhancement

#30 Update reg and log
  .gitignore
  app/static/styles/login.css
  app/templates/index.html
  app/templates/login.html
  app/templates/register.html
Labels: bug, enhancement

#33 Creates dash
  app/__init__.py
  app/static/styles/dash.css
  app/static/styles/landing.css
  app/templates/dash.html
Labels: bug, enhancement

#39 Flask config
  .gitignore
  app/.env
  app/__init__.py
Labels: enhancement

#40 Create settings page
  app/__init__.py
  app/static/styles/settings.css
  app/templates/dash/home.html
  app/templates/dash/settings.html
  app/templates/dash/settings/edit.html
  app/templates/dash/typer.html
Labels: enhancement

#42 Shantal
  README.md
  images/logo.png
  images/screenshot.png
Labels: documentation

#47 Create wsgi.py file
  wsgi.py
Labels: back-end

#45 Added Log out page, Toastr to the app, fixed bugs.
  app/__init__.py
  app/templates/base.html
  app/templates/dash/home.html
  app/templates/dash/settings.html
  requirements.txt
Labels: enhancement

#44 added workflow/lint.yml
  .github/workflows/lint.yml
  app/__init__.py
  app/db.py
Labels: back-end

#54 Authentication management
  app/__init__.py
  app/templates/dash/home.html
  app/templates/dash/settings.html
  app/templates/dash/settings/edit.html
Labels: bug, enhancement, back-end

#53 added cAdvisor container
  docker-compose.yml
Labels: enhancement, back-end

#59 Tweak typer UI
  app/__init__.py
  app/static/js/typer.js
  app/static/styles/typer.css
  app/templates/dash/settings.html
  app/templates/dash/settings/edit.html
  app/templates/dash/typer.html
Labels: enhancement, front-end

#60 added prometheus and grafana containers
  docker-compose.yml
  prometheus.yml
Labels: documentation, enhancement, back-end

#63 Added pytest testing
  pt_client.py
  requirements.txt
  setup.py
  test/test_api.py
  test/test_pt_client.py
Labels: documentation, enhancement, back-end

#64 Test part2
  app/__init__.py
Labels: bug, back-end

#68 added code snippets for JS and Python
  app/static/js/typer.js
Labels: enhancement, back-end
